package org.cyk.system.company.model;

public interface CompanyConstant {

	/* Business Service */
	
	String BUSINESS_SERVICE_COLLECTION_PRODUCT = "PRODUCT";
	String BUSINESS_SERVICE_COLLECTION_PAYMENT = "PAYMENT";
	String BUSINESS_SERVICE_COLLECTION_COMPANY = "COMPANY";
	String BUSINESS_SERVICE_COLLECTION_SALE = "SALE";
	String BUSINESS_SERVICE_COLLECTION_STOCK = "STOCK";
	String BUSINESS_SERVICE_COLLECTION_PRODUCTION = "PRODUCTION";
	String BUSINESS_SERVICE_COLLECTION_ACCOUNTING = "ACCOUNTING";
	
	/* Product */
	
	String STOCKING= "STOCKING";
	
	/* Gift card management */
	
	String GIFT_CARD_WORKFLOW = "GIFT_CARD_WORKFLOW";
	
	String GIFT_CARD_WORKFLOW_STATE_ASSIGNED = "GIFT_CARD_WORKFLOW_STATE_ASSIGNED";
	
	String GIFT_CARD_WORKFLOW_ALPHABET_SEND = "GIFT_CARD_WORKFLOW_ALPHABET_SEND";
	String GIFT_CARD_WORKFLOW_STATE_SENT = "GIFT_CARD_WORKFLOW_STATE_SENT";
	
	String GIFT_CARD_WORKFLOW_ALPHABET_RECEIVE = "GIFT_CARD_WORKFLOW_ALPHABET_RECEIVE";
	String GIFT_CARD_WORKFLOW_STATE_RECEIVED = "GIFT_CARD_WORKFLOW_STATE_RECEIVED";
	
	String GIFT_CARD_WORKFLOW_ALPHABET_SELL = "GIFT_CARD_WORKFLOW_ALPHABET_SELL";
	String GIFT_CARD_WORKFLOW_STATE_SOLD = "GIFT_CARD_WORKFLOW_STATE_SOLD";
	
	String GIFT_CARD_WORKFLOW_ALPHABET_USE = "GIFT_CARD_WORKFLOW_ALPHABET_USE";
	String GIFT_CARD_WORKFLOW_STATE_USED = "GIFT_CARD_WORKFLOW_STATE_USED";
	
}
