package org.cyk.system.company.model;

public interface CompanyConstant {

	/* Business Service */
	
	String BUSINESS_SERVICE_COLLECTION_PRODUCT = "PRODUCT";
	String BUSINESS_SERVICE_COLLECTION_PAYMENT = "PAYMENT";
	String BUSINESS_SERVICE_COLLECTION_COMPANY = "COMPANY";
	String BUSINESS_SERVICE_COLLECTION_SALE = "SALE";
	String BUSINESS_SERVICE_COLLECTION_STOCK = "STOCK";
	String BUSINESS_SERVICE_COLLECTION_PRODUCTION = "PRODUCTION";
	String BUSINESS_SERVICE_COLLECTION_ACCOUNTING = "ACCOUNTING";
	
	/* Product */
	
	String STOCKING= "STOCKING";
	
	/* Gift card management */
	
	String GIFT_CARD_WORKFLOW = "GIFT_CARD_WORKFLOW";
	
	String GIFT_CARD_WORKFLOW_STATE_ASSIGNED = "GIFT_CARD_WORKFLOW_STATE_ASSIGNED";
	
	String GIFT_CARD_WORKFLOW_ALPHABET_SEND = "GIFT_CARD_WORKFLOW_ALPHABET_SEND";
	String GIFT_CARD_WORKFLOW_STATE_SENT = "GIFT_CARD_WORKFLOW_STATE_SENT";
	
	String GIFT_CARD_WORKFLOW_ALPHABET_RECEIVE = "GIFT_CARD_WORKFLOW_ALPHABET_RECEIVE";
	String GIFT_CARD_WORKFLOW_STATE_RECEIVED = "GIFT_CARD_WORKFLOW_STATE_RECEIVED";
	
	String GIFT_CARD_WORKFLOW_ALPHABET_SELL = "GIFT_CARD_WORKFLOW_ALPHABET_SELL";
	String GIFT_CARD_WORKFLOW_STATE_SOLD = "GIFT_CARD_WORKFLOW_STATE_SOLD";
	
	String GIFT_CARD_WORKFLOW_ALPHABET_USE = "GIFT_CARD_WORKFLOW_ALPHABET_USE";
	String GIFT_CARD_WORKFLOW_STATE_USED = "GIFT_CARD_WORKFLOW_STATE_USED";
	
	/* File */
	
	String FILE_DOCUMENT_HEADER = "DOCUMENT_HEADER";
	String FILE_DOCUMENT_BACKGROUND = "DOCUMENT_BACKGROUND";
	String FILE_DOCUMENT_BACKGROUND_DRAFT = "DOCUMENT_BACKGROUND_DRAFT";
	
	/* Report */
	
	String REPORT_PRO_FORMA_INVOICE = "PRO_FORMA_INVOICE";
	String REPORT_INVOICE = "INVOICE";
	String REPORT_INVOICE_AND_PAYMENT_RECEIPT = "INVOICE_AND_PAYMENT_RECEIPT";
	String REPORT_PAYMENT_RECEIPT = "PAYMENT_RECEIPT";
	/*
	String REPORT_TEMPLATE_SALE_INVOICE_A4 = "SALE_INVOICE_A4";
	String REPORT_TEMPLATE_SALE_CASH_REGISTER_MOVEMENT_PAYMENT_RECEIPT_A4 = "SALE_CASH_REGISTER_MOVEMENT_PAYMENT_RECEIPT_A4";
	String REPORT_TEMPLATE_SALE_INVOICE_AND_SALE_CASH_REGISTER_MOVEMENT_PAYMENT_RECEIPT_A4 = "SALE_INVOICE_AND_SALE_CASH_REGISTER_MOVEMENT_PAYMENT_RECEIPT_A4";
	*/
	String REPORT_EMPLOYEE_EMPLOYMENT_CONTRACT = "EMPLOYEE_EMPLOYMENT_CONTRACT";
	String REPORT_EMPLOYEE_WORK_CERTIFICATE = "EMPLOYEE_WORK_CERTIFICATE";
	String REPORT_EMPLOYEE_EMPLOYMENT_CERTIFICATE = "EMPLOYEE_EMPLOYMENT_CERTIFICATE";
	
}
